### ISSUE TITLE
Getting email reminders on wrong days?

### ISSUE THREAD

**Issue by ameseee** [hillstew/paired-fe#100]
Hi paired team! You're great✨

Today I woke up to this email:
![image](https://user-images.githubusercontent.com/25447342/83885871-26bf4b00-a704-11ea-9f0c-6a7acb135335.png)

But on my paired account, I only see this:
![image](https://user-images.githubusercontent.com/25447342/83886312-43f41980-a704-11ea-9c71-585c2aae8a09.png)

I also got an email a few hours before that letting me know that a student booked a pairing, but the pairing had already come and gone.

Just wanted to let you know. Thanks!

**Comment by DanielEFrampton** [comment]
Thanks for letting us know, Amy! This was a side effect of a broader problem we had with our SendGrid API authentication, reported by an affected student on Wednesday. When we fixed it yesterday, SendGrid (unexpectedly) sent out its backlog of unsent emails, some of which were for old bookings. We're very sorry for the confusion, and for the missed pairings. We're looking into improving our error monitoring so we can catch this kind of thing earlier.
