### ISSUE TITLE
Multiple Pronouns / Fillable pronouns - Feature Request

### ISSUE THREAD

**Issue by DavisC0801** [hillstew/paired-fe#51]
For those like myself that use multiple pronouns or pronouns that change, a fillable option instead of a dropdown would be appreciated. The current choices do have a "prefer not to answer" and nonbinary pronouns which was appreciated, a fillable line may be more inclusive if it's not a complete refactor.

**Comment by hillstew** [comment]
Thank you for this feedback and this change should be live within the week!
