### ISSUE TITLE
Email Notifications for Bookings/Account Sign Up

### ISSUE THREAD

**Issue by BrennanAyers** [hillstew/paired-fe#52]
Instead of relying on having a page open, or allowing for Chrome notification permission on the Client's end, what if basic email notifications were implemented? This would also pull double duty of automatically implementing into people's GCal/iCal/Outlook when they receive it.
Sendgrid has a free tier: https://sendgrid.com/pricing/
But it looks like MailGun would be more scalable for these kinds of transactional emails: https://www.mailgun.com/

Additionally, it might be a good idea to include a, "Welcome!" email confirmation upon signing up as well.

**Comment by hillstew** [comment]
Thank you for making these issues! We had originally asked some of the users of the google sheet and received feedback that they would prefer the push notifications over email but that was a very small group of people we asked at the time. I also prefer the email route and could make email notifications optional for those that absolutely do not want them but still be able to provide them for those that do.

**Comment by Jonpatt92** [comment]
This is a great idea!
