### ISSUE TITLE
Unable to sign up

### ISSUE THREAD

**Issue by milevy1** [hillstew/paired-fe#68]
As a new user I am unable to sign up on paired.tech.
- I clicked sign in with Github
- I authorized the app with my github account
- I am redirected back to the paired.tech but the page is blank. I found this error message in the Chrome dev tools console on the blank page. I confirmed JavaScript is enabled for the page.

<img width="587" alt="Screen Shot 2019-05-18 at 10 52 24 AM" src="https://user-images.githubusercontent.com/36040194/57972832-f243ea00-795c-11e9-9042-175648f774ab.png">

- I attempted revoking the Github access token and then signing up again but get the same results.

I attempted using Google Chrome and Safari browsers.  Here is more information about my machine:
- macOS Version 10.14.4
- Google Chrome Version 74.0.3729.157 (Official Build) (64-bit)
- Safari Version 12.1 (14607.1.40.1.4)

If you need more information, let me know.
Matt

**Comment by hillstew** [comment]
Hi Matt! (@milevy1 ) Thank you for catching this and submitting the issue. We are pushing the fix now and should be updated within 10 minutes 😁

**Comment by milevy1** [comment]
Thanks @hillstew, I was able to successfully sign up just now.
