### ISSUE TITLE
Site wont let me log in or sign up

### ISSUE THREAD

**Issue by aripp2** [hillstew/paired-fe#69]
When I click Sign In With GitHub a blank small screen pops up for a second then goes back to the original sign in screen. Doesn't give me an error or any other options.

**Comment by hillstew** [comment]
Hi Amy! (@aripp2) 

I just tried and was able to sign in. Can you try again and let me know if you are still unable to login? We suspect that this is an issue with our backend shutting down after a period of inactivity. This is a priority that we plan to fix within the week.

**Comment by aripp2** [comment]
It is working now! Thank you!

Amy Rippeto
360-609-6387
