### ISSUE TITLE
Issues signing up

### ISSUE THREAD

**Issue by msimon42** [hillstew/paired-fe#86]
I am not able to sign in with github. The window pops up for a split second, then goes away.

**Comment by hillstew** [comment]
Hi @msimon42! Thank you, I will look into this tonight 🙂

**Comment by msimon42** [comment]
Hey, @hillstew, I was able to resolve the issue by changing some settings in my browser.

**Comment by hillstew** [comment]
Awesome @msimon42! If you get a chance, can you share the settings you had to change?

**Comment by msimon42** [comment]
I'm using Brave; I just suspended one of their built in privacy settings.

**Comment by hillstew** [comment]
Thank you! I am going to close this issue but if further problems arise feel free to submit another issue.
