### ISSUE TITLE
No pairing availability displaying

### ISSUE THREAD

**Issue by laurenlucero** [hillstew/paired-fe#92]
My rock put in his availability so I could schedule with him but it is not showing up for me.

**Comment by Not-Zorro** [comment]
Did you check to see if he updated his module he’s in? If not he may still be in last mods :)

**Comment by DanielEFrampton** [comment]
Thanks for making an issue, Lauren! Can you provide some more details? Most helpful would be:
 - your mentor's name
 - your name
 - what Mod and program you looked for your mentor under
 - what day you looked for his session under

Thanks!

**Comment by laurenlucero** [comment]
Actually my rock and he’s a repeater so same mod as last time
Karl Nielson
Lauren Lucero
FE mod 2
FE mod 2
I looked for him in Thursdays he said he put availability there we regularly pair them anyhow and wanted to use the app to keep a record of it. Thanks for the prompt reply!


Sent from Lauren’s iPhone
~peace~

**Comment by DanielEFrampton** [comment]
@laurenlucero I looked into it and @Not-Zorro called it, it looks like Karl's mod is still set to 1. If you search for that date under FE mod 1 you should find him, but if you could poke him and ask him to update it that'd be even better. Thanks again for reporting the issue! I'd rather double check than miss something going wrong under the hood.
