### ISSUE TITLE
Automatically scheduled?

### ISSUE THREAD

**Issue by DavidTTran** [hillstew/paired-fe#93]
I received a text message reminding/confirming that I have a pairing at noon, but when I look at my schedule nothing is present and I haven't confirmed any pairings.

**Comment by DanielEFrampton** [comment]
@DavidTTran Thanks for opening an issue! We have a known bug where if a booking is made and then canceled, a reminder about it is still sent out. Did you perchance have a booking made and canceled yesterday? If not I'll dig deeper.

**Comment by DavidTTran** [comment]
@DanielEFrampton Not that I'm aware of. I was under the impression that a pairing is only scheduled after confirmation from both parties, and when one party wishes to pair - the other first receives a notification. This message is the first I've received from the site.

**Comment by DanielEFrampton** [comment]
@DavidTTran Got it, thanks. As to how it works, paired sessions don't need to be confirmed by both sides, they're created the moment the "pairee" or lower-mod student clicks "Book Session." We don't yet have a "confirm" step, although it's on our future features list. But I'm not sure why you didn't get a notification about the booking in the first place, and will look into it. One last question: do you recall when it was that you added a phone number to your profile? (It's possible that the paired session was created before you had a phone number entered and the notification that you had been booked was sent via email.)

**Comment by pgoulding** [comment]
@DanielEFrampton I have had the same thing happen to me a few times now. I'll get an SMS notification that I have a pairing scheduled, then when I log in to check there's nothing there.

**Comment by DavidTTran** [comment]
@DanielEFrampton Believe I added my number around the time of the creation of my account, but I haven't received an email either.

**Comment by DanielEFrampton** [comment]
@DavidTTran @pgoulding Thank you both for clarifying, we'll look into this. If you have a moment can you both paste the notifications you received?

**Comment by pgoulding** [comment]
![Screenshot_20200319-105316](https://user-images.githubusercontent.com/11819050/77092986-fbb03f80-69cf-11ea-976f-797fae23ba85.png)

**Comment by DanielEFrampton** [comment]
Thanks, @pgoulding! That gives us a better idea of what's going on. The database agrees that you don't have any actual bookings. Our team has a hunch about what's happening and we're going to work on it this afternoon. If we don't have a solution by end of day we'll disable booking reminders until we do.

**Comment by DavidTTran** [comment]
![Screenshot_20200319-113524](https://user-images.githubusercontent.com/57076945/77097118-e76f4100-69d5-11ea-8d31-285866bd6afe.jpg)
