### ISSUE TITLE
Confirm booking reloads to schedule

### ISSUE THREAD

**Issue by melatran** [hillstew/paired-fe#95]
When I click on confirm booking, it reloads to the schedule website but nothing has been assigned to the schedule

**Comment by DanielEFrampton** [comment]
Thanks for submitting the issue, Melanie! Can you provide some more details about what link you clicked, and where? If it was a link in an email or text can you post the full message and when you received it? Thanks!

**Comment by melatran** [comment]
I tried it again and it worked. Thanks

**Comment by DanielEFrampton** [comment]
Righto! Thanks for the update.
