### ISSUE TITLE
booking emails not being sent

### ISSUE THREAD

**Issue by rachael-t** [hillstew/paired-fe#99]
Hi there! Someone booked a pairing session with me ~24 hours ago and I never received an email alerting me to the booking. I have received an email in the past from no_reply@paired.tech but this is the second time this I haven't received an email and I double checked my email was entered correctly. Let me know if I can provide any additional information.

**Comment by DanielEFrampton** [comment]
Hi Rachel! Thanks for letting us know. Can you provide your full name and/or email address and the name and/or email address of the person who booked with you? (If you'd like to keep them private, you can send it to me on Slack in a DM.) That'll give us enough to get started and then I'll reach out if we need more than that.

**Comment by rachael-t** [comment]
Yup! DMing you on Slack!

**Comment by DanielEFrampton** [comment]
We got to the bottom of it and working on a fix. We're really grateful you brought this to our attention! And I'm very sorry for the lost emails and for any missed appointments. This prompted us to plan to put some new tools in place for error monitoring, so hopefully we'll catch things like this earlier.

**Comment by DanielEFrampton** [comment]
Emails are working again after fixing our SendGrid authentication. Thanks again @rachael-t for bringing this to our attention!
